### PR TITLE
Scrum 24: Redesigned Individual team page

### PR DESCRIPTION
**Pull request by txiong002**
Redesigned grid to focus more on team information an make better use of space.  Tested view in multiple window sizes and fixed where needed.  Re-aligned items like social media icons and logo.  Added some styling to team info containers. 

Teams Main Page: changed from 1 column to 3 column when in mobile view
image

New Layout:
redesign_page

Different Screen sizes:
redesign_1024px
redesign_593px
redesign_395px

### CODE REVIEW

**Comment by dvan2** [comment]
Looking great.  Somethings I saw that we might wana change is the date.  I thought the default date that the data came with is a bit non user friendly. 
`function formatDate(dateString) {
  const options = { month: 'short', day: 'numeric', weekday: 'long' };
  return new Date(dateString).toLocaleDateString('en-US', options);
}
`
This is the function I used to formatdate.  You can just do something like `<h2>{formatDate(date_variable)}<h2>`.

Another thing I found was there is a little weird padding at the bottom of the upcoming schedule.
Lastly I think the @ character is a little weird.  It probably helps distinguish between home and away but I think we should just try to be consistent and use the `vs`.  If we want to distinguish between home and away games, may be use a different background color and add a legend?

You can try this color: #a8d08d for home team. Maybe add a hover #8cbf76.
Away team might be #ff6666.  With hover #e65c5c.

These are some of the colors I used in the PL table.

image

**Review by dvan2 — CHANGES_REQUESTED** [review]
Looking great.  Somethings I saw that we might wana change is the date.  I thought the default date that the data came with is a bit non user friendly. 
```
function formatDate(dateString) {
  const options = { month: 'short', day: 'numeric', weekday: 'long' };
  return new Date(dateString).toLocaleDateString('en-US', options);
}
```

This is the function I used to formatdate.  You can just do something like `<h2>{formatDate(date_variable)}<h2>`.

Another thing I found was there is a little weird padding at the bottom of the upcoming schedule.
Lastly I think the @ character is a little weird.  It probably helps distinguish between home and away but I think we should just try to be consistent and use the `vs`.  If we want to distinguish between home and away games, may be use a different background color and add a legend?

You can try this color: #a8d08d for home team. Maybe add a hover #8cbf76.
Away team might be #ff6666.  With hover #e65c5c.

These are some of the colors I used in the PL table and maybe you'd find it useful?

image

**Comment by txiong002** [comment]
Fixed padding, changed date forrmat and change time format to display time in PST region.  Also, I prefer the "vs" and "@" to distinguish between home and away game.  Thats how most sports event handle it.
image

**Comment by lebenpdx** [comment]
This got mentioned in last weeks lecture. For accessibility, when designing charts it's better to use different shades of a hue instead of multiple colors. I don't know if the colors used here cause an issue, but just something to keep in mind.

D3E3TSQW0AAJwfG

**Comment by dvan2** [comment]
image
I liked the old version with the divider between the player list with a little padding.
I guess we can stick with using the @ symbol if it's standard.  I think the date looks better now.  

Also maybe this is a good place to use the exported array `allTeamLogos` instead of calling getAllTeamNames().
image

**Comment by txiong002** [comment]
Added padding and borders to roster table.
image

**Comment by txiong002** [comment]
Added table for a team previous match results.
image

**Review by lebenpdx — APPROVED** [review]

**Review by dvan2 — CHANGES_REQUESTED** [review]
It looks like we have solid content now.  One suggestion I wana add is that now You can't fully see the text for team names and stadium.
image
I think it's important to be able to see the full names maybe just make the width bigger for the schedules and Previous Matches.  You can probably just have the upcoming schedule and previous match take more width and have the player rooster height come down a bit more: 
image

An easier fix might be to just have wrapping for the content.

Let me know if you agree/disagree.

**Comment by txiong002** [comment]
> It looks like we have solid content now. One suggestion I wana add is that now You can't fully see the text for team names and stadium. image I think it's important to be able to see the full names maybe just make the width bigger for the schedules and Previous Matches. You can probably just have the upcoming schedule and previous match take more width and have the player rooster height come down a bit more: image
> 
> An easier fix might be to just have wrapping for the content.
> 
> Let me know if you agree/disagree.

Removed Stadium column for now, to give more more to other columns: 
image

**Review by dvan2 — CHANGES_REQUESTED** [review]
Team full name is still not showing for previous matches. :
image

**Comment by txiong002** [comment]
> Team full name is still not showing for previous matches. : image

Added resize option to display all text for upcoming schedule.  Changed output display from word "win" to letter "W"
resize_columns
winsAndLosses

**Review by dvan2 — APPROVED** [review]

**Pull request merged**
