### PR TITLE
Scrum 20: Added chart, tables, and social media links to page

### PR DESCRIPTION
**Pull request by txiong002**
Added some features to the page like, Teams social media links, ranks, upcoming schedule, and roster.  Made changes to page to improve mobile view. 
redesigned_page
mobile_view
mobile_view_02

### CODE REVIEW

**Comment by lebenpdx** [comment]
Looks solid. A minor suggestion would be that the "Official Team Links" section seems a bit empty for the space it takes up. I would move the links to below the team logo. I also think the links can be assumed and don't need to be explicitly labeled.

chrome_uiEucvUCwA

**Comment by dvan2** [comment]
Looks great so far.  Here's a hover background color that I've been using on table rows that I like : `#f5f5f5`.  
image
It's very subtle and probably doesn't make much difference.

Other than that, I think I like Ben's suggestion with the links.
Also there is some empty space below the rooster list that I think might need a bit more work on. 
image
I like the Upcoming Schedule feed.

**Comment by txiong002** [comment]
> Looks solid. A minor suggestion would be that the "Official Team Links" section seems a bit empty for the space it takes up. I would move the links to below the team logo. I also think the links can be assumed and don't need to be explicitly labeled.
> 
> chrome_uiEucvUCwA

Removed link labels.  Moved social media icon under logo.
teams_page_remove_borders

**Comment by txiong002** [comment]
> Looks great so far. Here's a hover background color that I've been using on table rows that I like : `#f5f5f5`. image It's very subtle and probably doesn't make much difference.
> 
> Other than that, I think I like Ben's suggestion with the links. Also there is some empty space below the rooster list that I think might need a bit more work on. image I like the Upcoming Schedule feed.

Added hover and links to each player. Empty space now randomly displays a fan art. Added font size changes to table to work with mobile view.
teams_page_add_fanArt

**Review by lebenpdx — APPROVED** [review]
Looks good!

**Pull request merged**
